# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.BaseEventCreateQueryResourceObjectAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :properties,
    :time,
    :value,
    :unique_id,
    :metric
  ]

  @type t :: %__MODULE__{
    :properties => map(),
    :time => DateTime.t | nil,
    :value => float() | nil,
    :unique_id => String.t | nil,
    :metric => KlaviyoAPI.Model.EventCreateQueryV2ResourceObjectAttributesMetric.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:time, :datetime, nil)
     |> Deserializer.deserialize(:metric, :struct, KlaviyoAPI.Model.EventCreateQueryV2ResourceObjectAttributesMetric)
  end
end

