# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CampaignValuesRequestDtoResourceObjectAttributesTimeframe do
  @moduledoc """
  The timeframe to query for data within. The max length a timeframe can be is 1 year
  """

  @derive Jason.Encoder
  defstruct [
    :key,
    :start,
    :end
  ]

  @type t :: %__MODULE__{
    :key => String.t,
    :start => DateTime.t,
    :end => DateTime.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:start, :datetime, nil)
     |> Deserializer.deserialize(:end, :datetime, nil)
  end
end

