# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CampaignMessageAssignTemplateQueryResourceObjectRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :template
  ]

  @type t :: %__MODULE__{
    :template => KlaviyoAPI.Model.CampaignMessageAssignTemplateQueryResourceObjectRelationshipsTemplate.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:template, :struct, KlaviyoAPI.Model.CampaignMessageAssignTemplateQueryResourceObjectRelationshipsTemplate)
  end
end

