# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CampaignResponseObjectResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :status,
    :archived,
    :audiences,
    :send_options,
    :tracking_options,
    :send_strategy,
    :created_at,
    :scheduled_at,
    :updated_at,
    :send_time
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :status => String.t,
    :archived => boolean(),
    :audiences => KlaviyoAPI.Model.AudiencesSubObject.t,
    :send_options => KlaviyoAPI.Model.CampaignResponseObjectResourceAttributesSendOptions.t,
    :tracking_options => KlaviyoAPI.Model.CampaignResponseObjectResourceAttributesTrackingOptions.t,
    :send_strategy => KlaviyoAPI.Model.SendStrategySubObject.t,
    :created_at => DateTime.t,
    :scheduled_at => DateTime.t,
    :updated_at => DateTime.t,
    :send_time => DateTime.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:audiences, :struct, KlaviyoAPI.Model.AudiencesSubObject)
     |> Deserializer.deserialize(:send_options, :struct, KlaviyoAPI.Model.CampaignResponseObjectResourceAttributesSendOptions)
     |> Deserializer.deserialize(:tracking_options, :struct, KlaviyoAPI.Model.CampaignResponseObjectResourceAttributesTrackingOptions)
     |> Deserializer.deserialize(:send_strategy, :struct, KlaviyoAPI.Model.SendStrategySubObject)
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:scheduled_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:send_time, :datetime, nil)
  end
end

