# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CatalogItemUpdateQueryResourceObjectAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :title,
    :price,
    :description,
    :url,
    :image_full_url,
    :image_thumbnail_url,
    :images,
    :custom_metadata,
    :published
  ]

  @type t :: %__MODULE__{
    :title => String.t | nil,
    :price => float() | nil,
    :description => String.t | nil,
    :url => String.t | nil,
    :image_full_url => String.t | nil,
    :image_thumbnail_url => String.t | nil,
    :images => [String.t] | nil,
    :custom_metadata => map() | nil,
    :published => boolean() | nil
  }

  def decode(value) do
    value
  end
end

