# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CatalogItemCreateQueryResourceObjectAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :external_id,
    :integration_type,
    :title,
    :price,
    :catalog_type,
    :description,
    :url,
    :image_full_url,
    :image_thumbnail_url,
    :images,
    :custom_metadata,
    :published
  ]

  @type t :: %__MODULE__{
    :external_id => String.t,
    :integration_type => String.t | nil,
    :title => String.t,
    :price => float() | nil,
    :catalog_type => String.t | nil,
    :description => String.t,
    :url => String.t,
    :image_full_url => String.t | nil,
    :image_thumbnail_url => String.t | nil,
    :images => [String.t] | nil,
    :custom_metadata => map() | nil,
    :published => boolean() | nil
  }

  def decode(value) do
    value
  end
end

