# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CatalogItemResponseObjectResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :external_id,
    :title,
    :description,
    :price,
    :url,
    :image_full_url,
    :image_thumbnail_url,
    :images,
    :custom_metadata,
    :published,
    :created,
    :updated
  ]

  @type t :: %__MODULE__{
    :external_id => String.t | nil,
    :title => String.t | nil,
    :description => String.t | nil,
    :price => float() | nil,
    :url => String.t | nil,
    :image_full_url => String.t | nil,
    :image_thumbnail_url => String.t | nil,
    :images => [String.t] | nil,
    :custom_metadata => map() | nil,
    :published => boolean() | nil,
    :created => DateTime.t | nil,
    :updated => DateTime.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created, :datetime, nil)
     |> Deserializer.deserialize(:updated, :datetime, nil)
  end
end

