# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.ContactInformation do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :default_sender_name,
    :default_sender_email,
    :website_url,
    :organization_name,
    :street_address
  ]

  @type t :: %__MODULE__{
    :default_sender_name => String.t,
    :default_sender_email => String.t,
    :website_url => String.t,
    :organization_name => String.t,
    :street_address => KlaviyoAPI.Model.StreetAddress.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:street_address, :struct, KlaviyoAPI.Model.StreetAddress)
  end
end

