# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CouponCodeCreateJobCreateQueryResourceObjectAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :"coupon-codes"
  ]

  @type t :: %__MODULE__{
    :"coupon-codes" => KlaviyoAPI.Model.CouponCodeCreateJobCreateQueryResourceObjectAttributesCouponCodes.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:"coupon-codes", :struct, KlaviyoAPI.Model.CouponCodeCreateJobCreateQueryResourceObjectAttributesCouponCodes)
  end
end

