# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CouponResponseObjectResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :external_id,
    :description
  ]

  @type t :: %__MODULE__{
    :external_id => String.t,
    :description => String.t | nil
  }

  def decode(value) do
    value
  end
end

