# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CouponCodeCreateQueryResourceObject do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :attributes,
    :relationships
  ]

  @type t :: %__MODULE__{
    :type => KlaviyoAPI.Model.CouponCodeEnum.t,
    :attributes => KlaviyoAPI.Model.CouponCodeCreateQueryResourceObjectAttributes.t,
    :relationships => KlaviyoAPI.Model.CouponCodeCreateQueryResourceObjectRelationships.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type, :struct, KlaviyoAPI.Model.CouponCodeEnum)
     |> Deserializer.deserialize(:attributes, :struct, KlaviyoAPI.Model.CouponCodeCreateQueryResourceObjectAttributes)
     |> Deserializer.deserialize(:relationships, :struct, KlaviyoAPI.Model.CouponCodeCreateQueryResourceObjectRelationships)
  end
end

