# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.CouponCodeCreateQueryResourceObjectRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :coupon
  ]

  @type t :: %__MODULE__{
    :coupon => KlaviyoAPI.Model.CouponCodeCreateQueryResourceObjectRelationshipsCoupon.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:coupon, :struct, KlaviyoAPI.Model.CouponCodeCreateQueryResourceObjectRelationshipsCoupon)
  end
end

