# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.DataPrivacyCreateDeletionJobQueryResourceObjectAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :profile
  ]

  @type t :: %__MODULE__{
    :profile => KlaviyoAPI.Model.DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:profile, :struct, KlaviyoAPI.Model.DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile)
  end
end

