# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.EventResponseObjectResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :timestamp,
    :event_properties,
    :datetime,
    :uuid
  ]

  @type t :: %__MODULE__{
    :timestamp => integer() | nil,
    :event_properties => map() | nil,
    :datetime => DateTime.t | nil,
    :uuid => String.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:datetime, :datetime, nil)
  end
end

