# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.GetListRetrieveResponseCompoundDocumentDataAllOfAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :profile_count
  ]

  @type t :: %__MODULE__{
    :profile_count => integer() | nil
  }

  def decode(value) do
    value
  end
end

