# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.GetCatalogItemResponseCollectionCompoundDocument do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :data,
    :links,
    :included
  ]

  @type t :: %__MODULE__{
    :data => [KlaviyoAPI.Model.GetCatalogItemResponseCollectionCompoundDocumentDataInner.t],
    :links => KlaviyoAPI.Model.CollectionLinks.t,
    :included => [KlaviyoAPI.Model.CatalogVariantResponseObjectResource.t] | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, KlaviyoAPI.Model.GetCatalogItemResponseCollectionCompoundDocumentDataInner)
     |> Deserializer.deserialize(:links, :struct, KlaviyoAPI.Model.CollectionLinks)
     |> Deserializer.deserialize(:included, :list, KlaviyoAPI.Model.CatalogVariantResponseObjectResource)
  end
end

