# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.GetFlowMessageResponseCompoundDocumentDataAllOfRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :"flow-action",
    :template
  ]

  @type t :: %__MODULE__{
    :"flow-action" => KlaviyoAPI.Model.GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsFlowAction.t | nil,
    :template => KlaviyoAPI.Model.GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplate.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:"flow-action", :struct, KlaviyoAPI.Model.GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsFlowAction)
     |> Deserializer.deserialize(:template, :struct, KlaviyoAPI.Model.GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplate)
  end
end

