# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.GetAccounts4XxResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :errors
  ]

  @type t :: %__MODULE__{
    :errors => [KlaviyoAPI.Model.GetAccounts4XxResponseErrorsInner.t]
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:errors, :list, KlaviyoAPI.Model.GetAccounts4XxResponseErrorsInner)
  end
end

