# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.GetCampaignMessageResponseCompoundDocumentDataAllOfRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :campaign,
    :template
  ]

  @type t :: %__MODULE__{
    :campaign => KlaviyoAPI.Model.GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsCampaign.t | nil,
    :template => KlaviyoAPI.Model.GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsTemplate.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:campaign, :struct, KlaviyoAPI.Model.GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsCampaign)
     |> Deserializer.deserialize(:template, :struct, KlaviyoAPI.Model.GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsTemplate)
  end
end

