# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.GetProfileResponseDataAllOfAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :subscriptions,
    :predictive_analytics,
    :properties,
    :email,
    :first_name,
    :last_name,
    :title
  ]

  @type t :: %__MODULE__{
    :subscriptions => KlaviyoAPI.Model.Subscriptions.t | nil,
    :predictive_analytics => KlaviyoAPI.Model.PredictiveAnalytics.t | nil,
    :properties => map(),
    :email => String.t | nil,
    :first_name => String.t | nil,
    :last_name => String.t | nil,
    :title => String.t | nil,
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:subscriptions, :struct, KlaviyoAPI.Model.Subscriptions)
     |> Deserializer.deserialize(:predictive_analytics, :struct, KlaviyoAPI.Model.PredictiveAnalytics)
  end
end

