# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.GetEventResponseCollectionCompoundDocumentDataInnerAllOfRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :profile,
    :metric,
    :attributions
  ]

  @type t :: %__MODULE__{
    :profile => KlaviyoAPI.Model.GetEventResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile.t | nil,
    :metric => KlaviyoAPI.Model.GetEventResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsMetric.t | nil,
    :attributions => KlaviyoAPI.Model.GetEventResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsAttributions.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:profile, :struct, KlaviyoAPI.Model.GetEventResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile)
     |> Deserializer.deserialize(:metric, :struct, KlaviyoAPI.Model.GetEventResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsMetric)
     |> Deserializer.deserialize(:attributions, :struct, KlaviyoAPI.Model.GetEventResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsAttributions)
  end
end

