# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.MarketingSubscriptionParameters do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :consent,
    :consented_at
  ]

  @type t :: %__MODULE__{
    :consent => String.t,
    :consented_at => DateTime.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:consented_at, :datetime, nil)
  end
end

