# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.MetricResponseObjectResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :created,
    :updated,
    :integration
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :created => String.t | nil,
    :updated => String.t | nil,
    :integration => map() | nil
  }

  def decode(value) do
    value
  end
end

