# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.OnsiteSubscriptionCreateQueryResourceObjectAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :custom_source,
    :profile
  ]

  @type t :: %__MODULE__{
    :custom_source => String.t | nil,
    :profile => KlaviyoAPI.Model.OnsiteSubscriptionCreateQueryResourceObjectAttributesProfile.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:profile, :struct, KlaviyoAPI.Model.OnsiteSubscriptionCreateQueryResourceObjectAttributesProfile)
  end
end

