# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.OnsiteProfileMeta do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :patch_properties
  ]

  @type t :: %__MODULE__{
    :patch_properties => KlaviyoAPI.Model.ProfileMetaPatchProperties.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:patch_properties, :struct, KlaviyoAPI.Model.ProfileMetaPatchProperties)
  end
end

