# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.PostCatalogItemUpdateJobResponseData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :id,
    :attributes,
    :relationships,
    :links
  ]

  @type t :: %__MODULE__{
    :type => KlaviyoAPI.Model.CatalogItemBulkUpdateJobEnum.t,
    :id => String.t,
    :attributes => KlaviyoAPI.Model.CouponCodeCreateJobResponseObjectResourceAttributes.t,
    :relationships => KlaviyoAPI.Model.GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships.t | nil,
    :links => KlaviyoAPI.Model.ObjectLinks.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type, :struct, KlaviyoAPI.Model.CatalogItemBulkUpdateJobEnum)
     |> Deserializer.deserialize(:attributes, :struct, KlaviyoAPI.Model.CouponCodeCreateJobResponseObjectResourceAttributes)
     |> Deserializer.deserialize(:relationships, :struct, KlaviyoAPI.Model.GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships)
     |> Deserializer.deserialize(:links, :struct, KlaviyoAPI.Model.ObjectLinks)
  end
end

