# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.PostFlowSeriesResponseDtoDataAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :results,
    :date_times
  ]

  @type t :: %__MODULE__{
    :results => [KlaviyoAPI.Model.SeriesData.t],
    :date_times => [DateTime.t]
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:results, :list, KlaviyoAPI.Model.SeriesData)
     |> Deserializer.deserialize(:date_times, :list, KlaviyoAPI.Model.DateTime)
  end
end

