# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.PostFlowSeriesResponseDtoData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :attributes,
    :relationships,
    :links
  ]

  @type t :: %__MODULE__{
    :type => KlaviyoAPI.Model.FlowSeriesReportEnum.t,
    :attributes => KlaviyoAPI.Model.PostFlowSeriesResponseDtoDataAttributes.t,
    :relationships => KlaviyoAPI.Model.PostFlowValuesResponseDtoDataRelationships.t | nil,
    :links => KlaviyoAPI.Model.ObjectLinks.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type, :struct, KlaviyoAPI.Model.FlowSeriesReportEnum)
     |> Deserializer.deserialize(:attributes, :struct, KlaviyoAPI.Model.PostFlowSeriesResponseDtoDataAttributes)
     |> Deserializer.deserialize(:relationships, :struct, KlaviyoAPI.Model.PostFlowValuesResponseDtoDataRelationships)
     |> Deserializer.deserialize(:links, :struct, KlaviyoAPI.Model.ObjectLinks)
  end
end

