# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.PostFlowValuesResponseDtoDataAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :results
  ]

  @type t :: %__MODULE__{
    :results => [KlaviyoAPI.Model.ValuesData.t]
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:results, :list, KlaviyoAPI.Model.ValuesData)
  end
end

