# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.PredictiveAnalytics do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :historic_clv,
    :predicted_clv,
    :total_clv,
    :historic_number_of_orders,
    :predicted_number_of_orders,
    :average_days_between_orders,
    :average_order_value,
    :churn_probability,
    :expected_date_of_next_order
  ]

  @type t :: %__MODULE__{
    :historic_clv => float() | nil,
    :predicted_clv => float() | nil,
    :total_clv => float() | nil,
    :historic_number_of_orders => integer() | nil,
    :predicted_number_of_orders => float() | nil,
    :average_days_between_orders => float() | nil,
    :average_order_value => float() | nil,
    :churn_probability => float() | nil,
    :expected_date_of_next_order => DateTime.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:expected_date_of_next_order, :datetime, nil)
  end
end

