# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.ProfilePartialUpdateQueryResourceObject do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :id,
    :attributes,
    :meta
  ]

  @type t :: %__MODULE__{
    :type => KlaviyoAPI.Model.ProfileEnum.t,
    :id => String.t,
    :attributes => KlaviyoAPI.Model.ProfilePartialUpdateQueryResourceObjectAttributes.t,
    :meta => KlaviyoAPI.Model.ProfileMeta.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type, :struct, KlaviyoAPI.Model.ProfileEnum)
     |> Deserializer.deserialize(:attributes, :struct, KlaviyoAPI.Model.ProfilePartialUpdateQueryResourceObjectAttributes)
     |> Deserializer.deserialize(:meta, :struct, KlaviyoAPI.Model.ProfileMeta)
  end
end

