# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.ProfileImportJobCreateQueryResourceObjectRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :lists
  ]

  @type t :: %__MODULE__{
    :lists => KlaviyoAPI.Model.ProfileImportJobCreateQueryResourceObjectRelationshipsLists.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:lists, :struct, KlaviyoAPI.Model.ProfileImportJobCreateQueryResourceObjectRelationshipsLists)
  end
end

