# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.ProfileMetaPatchProperties do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :append,
    :unappend,
    :unset
  ]

  @type t :: %__MODULE__{
    :append => map() | nil,
    :unappend => map() | nil,
    :unset => KlaviyoAPI.Model.ProfileMetaPatchPropertiesUnset.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:unset, :struct, KlaviyoAPI.Model.ProfileMetaPatchPropertiesUnset)
  end
end

