# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.ProfileMergeQueryResourceObject do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :id,
    :relationships
  ]

  @type t :: %__MODULE__{
    :type => KlaviyoAPI.Model.ProfileMergeEnum.t,
    :id => String.t,
    :relationships => KlaviyoAPI.Model.ProfileMergeQueryResourceObjectRelationships.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type, :struct, KlaviyoAPI.Model.ProfileMergeEnum)
     |> Deserializer.deserialize(:relationships, :struct, KlaviyoAPI.Model.ProfileMergeQueryResourceObjectRelationships)
  end
end

