# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.RelationshipLinks do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :self,
    :related
  ]

  @type t :: %__MODULE__{
    :self => String.t,
    :related => String.t
  }

  def decode(value) do
    value
  end
end

