# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.SegmentListResponseObjectResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :created,
    :updated
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :created => DateTime.t | nil,
    :updated => DateTime.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created, :datetime, nil)
     |> Deserializer.deserialize(:updated, :datetime, nil)
  end
end

