# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.ServerBisSubscriptionCreateQueryResourceObjectRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :variant
  ]

  @type t :: %__MODULE__{
    :variant => KlaviyoAPI.Model.ServerBisSubscriptionCreateQueryResourceObjectRelationshipsVariant.t
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:variant, :struct, KlaviyoAPI.Model.ServerBisSubscriptionCreateQueryResourceObjectRelationshipsVariant)
  end
end

