# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.StaticScheduleOptions do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :datetime,
    :is_local,
    :send_past_recipients_immediately
  ]

  @type t :: %__MODULE__{
    :datetime => DateTime.t,
    :is_local => boolean() | nil,
    :send_past_recipients_immediately => boolean() | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:datetime, :datetime, nil)
  end
end

