# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.StreetAddress do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :address1,
    :address2,
    :city,
    :region,
    :country,
    :zip
  ]

  @type t :: %__MODULE__{
    :address1 => String.t,
    :address2 => String.t,
    :city => String.t,
    :region => String.t,
    :country => String.t,
    :zip => String.t
  }

  def decode(value) do
    value
  end
end

