# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.SubscriptionDeleteJobCreateQueryResourceObject do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :attributes,
    :relationships
  ]

  @type t :: %__MODULE__{
    :type => KlaviyoAPI.Model.ProfileSubscriptionBulkDeleteJobEnum.t,
    :attributes => KlaviyoAPI.Model.SubscriptionDeleteJobCreateQueryResourceObjectAttributes.t,
    :relationships => KlaviyoAPI.Model.SubscriptionDeleteJobCreateQueryResourceObjectRelationships.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:attributes, :struct, KlaviyoAPI.Model.SubscriptionDeleteJobCreateQueryResourceObjectAttributes)
     |> Deserializer.deserialize(:relationships, :struct, KlaviyoAPI.Model.SubscriptionDeleteJobCreateQueryResourceObjectRelationships)
  end
end

