# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.SubscriptionCreateJobCreateQueryResourceObjectRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :list
  ]

  @type t :: %__MODULE__{
    :list => KlaviyoAPI.Model.SubscriptionCreateJobCreateQueryResourceObjectRelationshipsList.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:list, :struct, KlaviyoAPI.Model.SubscriptionCreateJobCreateQueryResourceObjectRelationshipsList)
  end
end

