# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.TagCreateQueryResourceObjectRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :"tag-group"
  ]

  @type t :: %__MODULE__{
    :"tag-group" => KlaviyoAPI.Model.TagCreateQueryResourceObjectRelationshipsTagGroup.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:"tag-group", :struct, KlaviyoAPI.Model.TagCreateQueryResourceObjectRelationshipsTagGroup)
  end
end

