# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.TagCreateQueryResourceObject do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :attributes,
    :relationships
  ]

  @type t :: %__MODULE__{
    :type => KlaviyoAPI.Model.TagEnum.t,
    :attributes => KlaviyoAPI.Model.TagResponseObjectResourceAttributes.t,
    :relationships => KlaviyoAPI.Model.TagCreateQueryResourceObjectRelationships.t | nil
  }

  alias KlaviyoAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type, :struct, KlaviyoAPI.Model.TagEnum)
     |> Deserializer.deserialize(:attributes, :struct, KlaviyoAPI.Model.TagResponseObjectResourceAttributes)
     |> Deserializer.deserialize(:relationships, :struct, KlaviyoAPI.Model.TagCreateQueryResourceObjectRelationships)
  end
end

