# NOTE: This file is auto generated by OpenAPI Generator 7.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule KlaviyoAPI.Model.TemplateCreateQueryResourceObjectAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :editor_type,
    :html,
    :text
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :editor_type => String.t,
    :html => String.t | nil,
    :text => String.t | nil
  }

  def decode(value) do
    value
  end
end

